modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPLv3"
issueTrackerURL="${github}/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${github}"
logoFile="icon.png"
authors="${author}"
description="${description}"
[[dependencies.chunkyborder]]
   modId="forge"
   mandatory=true
   versionRange="[56,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chunkyborder]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.21.6,1.22)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chunkyborder]]
  modId="chunky"
  mandatory=true
  versionRange="[${target},)"
  ordering="BEFORE"
  side="BOTH"
[[mixins]]
config="chunkyborder.mixins.json"
