name: ChunkyBorder
version: ${version}
main: ${group}.chunkyborder.ChunkyBorder
api-version: "1.13"
depend: [Chunky]
softdepend: [dynmap, BlueMap, Pl3xMap]
load: POSTWORLD
authors: [${author}]
description: ${description}
website: https://www.spigotmc.org/resources/chunkyborder.84278/
commands:
  chunkyborder:
    description: Set a border
    aliases: [cb]
    permission: chunkyborder.chunkyborder
    usage: /chunkyborder <add|remove>
permissions:
  chunkyborder.chunkyborder:
    description: Set a border
    default: op
  chunkyborder.bypass.move:
    description: Bypass border movement checks
    default: false
  chunkyborder.bypass.place:
    description: Bypass border block placement checks
    default: false
