modLoader="javafml"
loaderVersion="[3,)"
license="GNU GPLv3"
issueTrackerURL="${github}/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${github}"
logoFile="icon.png"
authors="${author}"
description="${description}"
[[dependencies.chunkyborder]]
   modId="neoforge"
   type="required"
   versionRange="[21.6.0-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chunkyborder]]
   modId="minecraft"
   type="required"
   versionRange="[1.21.6,1.22)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chunkyborder]]
  modId="chunky"
  type="required"
  versionRange="[${target},)"
  ordering="BEFORE"
  side="BOTH"
[[mixins]]
config="chunkyborder.mixins.json"
